name: Lifegoals_DockerImage

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  angular_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: npm install
        run: npm ci

      # Crear environment.ts dinámicamente
      - name: Create environment.ts
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.ts <<EOF
          export const environment = {
            production: true,
            firebase: {
              apiKey: '${{ secrets.apiKey }}',
              authDomain: '${{ secrets.authDomain }}',
              projectId: '${{ secrets.projectId }}',
              storageBucket: '${{ secrets.storageBucket }}',
              messagingSenderId: '${{ secrets.messagingSenderId }}',
              appId: '${{ secrets.appId }}'
            }
          };
          EOF

      - name: build
        run: npm run build -- --configuration=production

      - name: Login a Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build y Push imagen Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lifegoals:latest

      # Trigger deploy en Render
      - name: Trigger Render Deploy
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
